# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Benyomin Hagalili - Academic Homepage
  he: בנימן הגלילי - דף הבית אקדמי
email: benyomin-[at]-benyomin.net
description:
  en: MA student in Israel-Studies at Sde Boker.
  he: אני גר בשדה בוקר
index:
  en:
  he: accueil.html
feed:
  en: /feed.xml
  he: /flux.xml
baseurl:  # the subpath of your site, e.g. /blog
url: "http://paynito.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  paynito

# Build settings
markdown: kramdown
